(fix) temporary audio file not removed.
In audio.py file:
texts = text_splitter.split_text(transcript)

Threw an exception.
TypeError: expected string or bytes-like object, got 'OpenAIObject'

This causes the temporary file to persist.

Signed-off-by: Michael Tan <tan.michael@mac.com>