(fix) temporary audio file not removed. (#377)
* (fix) temporary audio file not removed.

In audio.py file:
texts = text_splitter.split_text(transcript)

Threw an exception.
TypeError: expected string or bytes-like object, got 'OpenAIObject'

This causes the temporary file to persist.

Signed-off-by: Michael Tan <tan.michael@mac.com>

* Additionally fix the reason why text splitting threw the exception.

Default response format is JSON.

Signed-off-by: Michael Tan <tan.michael@mac.com>

---------

Signed-off-by: Michael Tan <tan.michael@mac.com>